name: instadam
description: "InstaDAM Grup 5"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  shared_preferences: ^2.5.4

  # Firebase (versions compatibles)
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logoApp.png
    - assets/DES.jpg
    - assets/gordo.jpg
    - assets/gos.jpg
    - assets/imatge.png
    - assets/dam2.jpg
    - assets/commit100.jpeg