// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwlnx38kZkQpRKdkr894bWFZTODDoR-to',
    appId: '1:844800620734:web:dc2d2e6f344f679dca06ef',
    messagingSenderId: '844800620734',
    projectId: 'instadam-88c6a',
    authDomain: 'instadam-88c6a.firebaseapp.com',
    storageBucket: 'instadam-88c6a.firebasestorage.app',
    measurementId: 'G-WMK1X9V680',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOspj6B-oJ1L4ZmNy7I6pkOe2VXBl3dqA',
    appId: '1:844800620734:android:ef81efd54a370a51ca06ef',
    messagingSenderId: '844800620734',
    projectId: 'instadam-88c6a',
    storageBucket: 'instadam-88c6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwT-ftJboZ0NB8vADJ92lo4uGiI8KUhGQ',
    appId: '1:844800620734:ios:726c4178cbbbf8cfca06ef',
    messagingSenderId: '844800620734',
    projectId: 'instadam-88c6a',
    storageBucket: 'instadam-88c6a.firebasestorage.app',
    iosBundleId: 'com.example.instadam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwT-ftJboZ0NB8vADJ92lo4uGiI8KUhGQ',
    appId: '1:844800620734:ios:726c4178cbbbf8cfca06ef',
    messagingSenderId: '844800620734',
    projectId: 'instadam-88c6a',
    storageBucket: 'instadam-88c6a.firebasestorage.app',
    iosBundleId: 'com.example.instadam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwlnx38kZkQpRKdkr894bWFZTODDoR-to',
    appId: '1:844800620734:web:839460fd13767c48ca06ef',
    messagingSenderId: '844800620734',
    projectId: 'instadam-88c6a',
    authDomain: 'instadam-88c6a.firebaseapp.com',
    storageBucket: 'instadam-88c6a.firebasestorage.app',
    measurementId: 'G-BY2HPRBJLE',
  );

}